lib/riiif: autoload Riiif::Image class
Removed in
https://github.com/curationexperts/riiif/commit/f1556340091ea008cd1cb46cce82287d80b74874,
but this can cause init errors of the 'undefined method `file_resolver=' for
Riiif::Image:Class (NoMethodError)' variety.